### PR TITLE
Fix FromIterator for HexBounds

### LINKED ISSUE #213: HexBounds FromIterator Uses Incomplete Algorithm
**Describe the bug**
`HexBounds` collection algorithm misses hexagons.

**To Reproduce**
```rust
let mut rhombus = Vec::new();

for x in 0..5 {
    for y in 0..5 {
        rhombus.push(hexx::Hex::new(x, y));
    }
}

let bounds: hexx::HexBounds = rhombus.iter().copied().collect();

for hex in rhombus.iter() {
    assert!(bounds.is_in_bounds(*hex), "Hex {:?} is not in bounds", hex);
}
```
This assertion fails on any hex in the highlighted regions:

Image

**Expected behavior**
The `FromIterator` impl should account for high and low `s` coordinates when deciding how big to make itself.

### PR DESCRIPTION
**Pull request by CrystalKeck27**
Hoo boy this wasn't easy.

Fixes #213

This algorithm should be giving the smallest possible hexagon surrounding the hexes given.
Runs in linear time, and doesn't collect on the iterator, so constant space complexity.

Added tests for this implementation in the following shapes:
- Hexagon
- Rhombus
- Wedge (Triangle)
- Line
- Point
- Empty Iterator

### CODE REVIEW

File: src/bounds.rs [hunk 1]
```diff
@@ -143,16 +143,103 @@ impl HexBounds {
...
+
+        let count = iter
+            .into_iter()
+            .map(|hex| {
+                minx = minx.min(hex.x);
+                miny = miny.min(hex.y);
+                minz = minz.min(hex.z());
+                maxx = maxx.max(hex.x);
+                maxy = maxy.max(hex.y);
+                maxz = maxz.max(hex.z());
```
Comment (ManevilleF) [inline src/bounds.rs:161]:
```suggestion
        let mut min = IVec3::MAX;
        let mut max = IVec3::MIN;
       
        let count = iter
            .into_iter()
            .map(|hex| {
                min = min.min(hex.as_ivec3());
                max = max.max(hex.as_ivec3());
```
Nipick, we could gain in clarity using glam's `IVec3` struct and methods directly, for the same result.
If you prefer avoiding using `glam` we could use a [i32; 3] for `min` and `max`

File: src/bounds.rs [hunk 2]
```diff
@@ -143,16 +143,103 @@ impl HexBounds {
...
+        let mut minx = i32::MAX;
+        let mut miny = i32::MAX;
+        let mut minz = i32::MAX;
+        let mut maxx = i32::MIN;
+        let mut maxy = i32::MIN;
+        let mut maxz = i32::MIN;
+
+        let count = iter
+            .into_iter()
+            .map(|hex| {
```
Comment (ManevilleF) [inline src/bounds.rs:155]: Since we don't transform the value and return nothing from the block, I wonder if using `inspect` or `foreach` might be faster. WDYT ?

**Review by ManevilleF — COMMENTED** [review]
Thank you very much for this contribution, well explained and tested !

Could you add a high level explanation on the algorithm itself ? Even if each step is explained with a comment I'm not confident on some operations.

File: src/bounds.rs (hunk 2 above)
Comment (CrystalKeck27) [reply src/bounds.rs]: I found a way to get around counting the whole iter. Turns out, I only need to know if it's empty or not.

File: src/bounds.rs (hunk 1 above)
Comment (CrystalKeck27) [reply src/bounds.rs]: The reason why I used separate variables here is that it helped me think through the problem. These items should be *thought* about as separate entities. I think using a Glam struct should be fine for that as long as it is made clear what the algorithm is actually doing.

I'm test running swapping in the glam struct right now so we can compare.

**Comment by CrystalKeck27** [comment]
Comments have been added, variable names cleaned up, and variables merged into glam structs when possible.

**Review by ManevilleF — APPROVED** [review]

**Comment by CrystalKeck27** [comment]
Will clean up the clippy and docs stuff when I have time later today
